Repository kyu-kim-kr/sidedish, pull requests merged in 2021-04, with the labels that each got.

#16 [BE] Add/repo
  backend/src/main/java/develop/baminchan/entity/Banchan.java
  backend/src/main/java/develop/baminchan/entity/User.java
  backend/src/main/java/develop/baminchan/repository/BanchanRepository.java
  backend/src/main/java/develop/baminchan/repository/CategoryRepository.java
Labels: BE

#17 [#9] Tag, Button 컴포넌트 생성
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/common/Button.jsx
  frontend/src/common/Tag.jsx
  frontend/src/index.js
  frontend/src/reset.css
Labels: FE, enhancement

#20 [#1] 헤더 관련 Component 만들기 (완성)
  frontend/.gitignore
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/Header/Header.jsx
  frontend/src/Header/partial/Logo.jsx
  frontend/src/Header/partial/MenuItem.jsx
  frontend/src/Header/partial/MenuItemDropdown.jsx
  frontend/src/Header/partial/SearchBar.jsx
  frontend/src/common/CommonStyledCSS.jsx
  frontend/src/common/theme.jsx
Labels: FE, enhancement

#21 fix: 삼항연산자로 텍스트 바뀌도록 수정
  frontend/src/common/Button.jsx
  frontend/src/common/Tag.jsx
Labels: FE, enhancement

#22 [BE] Add/service
  backend/build.gradle
  backend/src/main/java/develop/baminchan/controller/BanchanController.java
  backend/src/main/java/develop/baminchan/controller/CategoryController.java
  backend/src/main/java/develop/baminchan/entity/Banchan.java
  backend/src/main/java/develop/baminchan/entity/Category.java
  backend/src/main/java/develop/baminchan/entity/banchan/Badge.java
  backend/src/main/java/develop/baminchan/entity/banchan/BanchanDetail.java
  backend/src/main/java/develop/baminchan/entity/banchan/DeliveryType.java
  backend/src/main/java/develop/baminchan/repository/BanchanRepository.java
  backend/src/main/java/develop/baminchan/repository/CategoryRepository.java
  backend/src/main/java/develop/baminchan/service/BanchanService.java
  backend/src/main/java/develop/baminchan/service/CategoryService.java
  backend/src/test/java/develop/baminchan/SidedishApplicationTests.java
Labels: BE

#26 [BE] Feat/jsonarray
  backend/src/main/java/develop/baminchan/controller/BanchanController.java
  backend/src/main/java/develop/baminchan/dto/BanchanDto.java
  backend/src/main/java/develop/baminchan/entity/Banchan.java
  backend/src/main/java/develop/baminchan/entity/BanchanDetail.java
  backend/src/main/java/develop/baminchan/entity/banchan/Badge.java
  backend/src/main/java/develop/baminchan/entity/banchan/BanchanDetail.java
  backend/src/main/java/develop/baminchan/entity/banchan/DeliveryType.java
  backend/src/main/java/develop/baminchan/service/BanchanService.java
  backend/src/main/resources/application.properties
Labels: BE, help wanted, study

#30 [FE] ProductCard 컴포넌트 생성 완료
  frontend/src/common/Button.jsx
  frontend/src/common/ProductCard.jsx
  frontend/src/common/Tag.jsx
  frontend/src/common/Title.jsx
  frontend/src/common/ref.jsx
  frontend/src/common/useFetch.jsx
Labels: FE, enhancement

#31 [FE] 디렉토리 구조 변경, theme 스타일 추가, 키값 변경
  frontend/src/Header/Header.jsx
  frontend/src/Header/partial/Logo.jsx
  frontend/src/Header/partial/MenuItem.jsx
  frontend/src/Header/partial/MenuItemDropdown.jsx
  frontend/src/Header/partial/SearchBar.jsx
  frontend/src/hooks/useFetch.jsx
  frontend/src/ref.jsx
  frontend/src/style/CommonStyledCSS.jsx
  frontend/src/style/reset.css
  frontend/src/style/theme.jsx
  frontend/src/utilComponent/Button.jsx
  frontend/src/utilComponent/ProductCard.jsx
  frontend/src/utilComponent/Tag.jsx
  frontend/src/utilComponent/Title.jsx
Labels: FE, enhancement

#33 [FE] 디렉토리 구조 변경에 따른 import 설정 변경 및 theme 스타일 추가에 따른 스타일 변경
  frontend/src/App.js
  frontend/src/header/Header.jsx
  frontend/src/header/partial/Logo.jsx
  frontend/src/header/partial/MenuItem.jsx
  frontend/src/header/partial/MenuItemDropdown.jsx
  frontend/src/header/partial/SearchBar.jsx
  frontend/src/style/theme.jsx
Labels: FE, enhancement

#32 [BE] Feat/detailpage
  backend/src/main/java/develop/baminchan/controller/BanchanController.java
  backend/src/main/java/develop/baminchan/dto/BanchanDto.java
  backend/src/main/java/develop/baminchan/dto/banchan/BanchanDetailDataDto.java
  backend/src/main/java/develop/baminchan/dto/banchan/BanchanDetailDto.java
  backend/src/main/java/develop/baminchan/dto/util/StringConvertor.java
  backend/src/main/java/develop/baminchan/entity/Banchan.java
  backend/src/main/java/develop/baminchan/entity/BanchanDetail.java
  backend/src/main/java/develop/baminchan/entity/banchan/BanchanDetail.java
  backend/src/main/java/develop/baminchan/entity/banchan/BanchanDetailData.java
  backend/src/main/java/develop/baminchan/service/BanchanService.java
Labels: BE, enhancement, help wanted, study

#36 [BE] Feat/category
  backend/src/main/java/develop/baminchan/controller/BanchanController.java
  backend/src/main/java/develop/baminchan/controller/CategoryController.java
  backend/src/main/java/develop/baminchan/dto/CategoryDto.java
  backend/src/main/java/develop/baminchan/dto/banchan/BanchanDetailDataDto.java
  backend/src/main/java/develop/baminchan/entity/Banchan.java
  backend/src/main/java/develop/baminchan/entity/Category.java
  backend/src/main/java/develop/baminchan/repository/BanchanRepository.java
  backend/src/main/java/develop/baminchan/repository/CategoryRepository.java
  backend/src/main/java/develop/baminchan/service/CategoryService.java
  backend/src/test/java/develop/baminchan/SidedishApplicationTests.java
Labels: BE, enhancement

#39 [FE] SubContents 1차 완성 (Carousel Slider)
  frontend/src/App.js
  frontend/src/header/partial/MenuItem.jsx
  frontend/src/header/partial/MenuItemDropdown.jsx
  frontend/src/hooks/useFetch2.jsx
  frontend/src/style/CommonStyledCSS.jsx
  frontend/src/subContents/SubContents.jsx
  frontend/src/subContents/partial/AllSubContentsView.jsx
  frontend/src/subContents/partial/SubContentsSection.jsx
  frontend/src/utilComponent/ArrowButton.jsx
  frontend/src/utilComponent/Carousel.jsx
Labels: FE, enhancement

#40 [BE] Feat/non-category
  backend/src/main/java/develop/baminchan/controller/CategoryController.java
  backend/src/main/java/develop/baminchan/controller/Message.java
  backend/src/main/java/develop/baminchan/service/CategoryService.java
Labels: BE, enhancement

#44 [BE] Feat/taggedbanchan
  backend/src/main/java/develop/baminchan/controller/BanchanController.java
  backend/src/main/java/develop/baminchan/controller/Message.java
  backend/src/main/java/develop/baminchan/dto/banchan/BanchanDetailDataDto.java
  backend/src/main/java/develop/baminchan/dto/banchan/BanchanDetailDto.java
  backend/src/main/java/develop/baminchan/entity/banchan/BanchanDetailData.java
  backend/src/main/java/develop/baminchan/repository/BanchanRepository.java
  backend/src/main/java/develop/baminchan/service/BanchanService.java
Labels: BE, enhancement

#45 fix : 데이터 구분법 변경
  backend/src/main/java/develop/baminchan/dto/util/StringConvertor.java
Labels: BE

#47 [FE] MainContents 부분 구현 완료
  frontend/src/hooks/useFetch.jsx
  frontend/src/mainContents/MainContents.jsx
  frontend/src/mainContents/MainContentsContainer.jsx
  frontend/src/mainContents/TabList.jsx
  frontend/src/utilComponent/ProductCard.jsx
  frontend/src/utilComponent/Title.jsx
Labels: FE, enhancement

#48 [BE] Feat/order
  backend/src/main/java/develop/baminchan/controller/OrderController.java
  backend/src/main/java/develop/baminchan/dto/banchan/BanchanDetailDto.java
  backend/src/main/java/develop/baminchan/entity/Order.java
  backend/src/main/java/develop/baminchan/entity/banchan/BanchanDetail.java
  backend/src/main/java/develop/baminchan/repository/OrderRepository.java
  backend/src/main/java/develop/baminchan/service/OrderService.java
Labels: BE

#51 [FE] Carousel (Slider) 컴포넌트의 재사용성을 위해 리팩토링
  frontend/src/hooks/useFetch2.jsx
  frontend/src/subContents/partial/SubContentsSection.jsx
  frontend/src/utilComponent/ArrowButton.jsx
  frontend/src/utilComponent/Carousel.jsx
  frontend/src/utilComponent/carousel/Carousel.jsx
  frontend/src/utilComponent/carousel/CarouselArrowBtn.jsx
Labels: FE, enhancement

#52 [BE] Feat/GitHub oauth
  backend/build.gradle
  backend/src/main/java/develop/baminchan/SidedishApplication.java
  backend/src/main/java/develop/baminchan/entity/Order.java
  backend/src/main/resources/application.properties
Labels: BE, enhancement

#56 [FE] 상세정보 창 (Detail - Modal) 1차 완성
  frontend/public/img/testimg.jpg
  frontend/src/App.js
  frontend/src/detail/Detail.jsx
  frontend/src/detail/DetailBottom.jsx
  frontend/src/detail/DetailTop.jsx
  frontend/src/detail/DetailTopGallery.jsx
  frontend/src/detail/DetailTopInfo.jsx
  frontend/src/header/partial/Logo.jsx
  frontend/src/hooks/useFetch.jsx
  frontend/src/hooks/useFetch2.jsx
  frontend/src/mainContents/MainContentsContainer.jsx
  frontend/src/style/theme.jsx
  frontend/src/subContents/SubContents.jsx
  frontend/src/subContents/partial/SubContentsSection.jsx
  frontend/src/util/util.js
  frontend/src/utilComponent/Button.jsx
  frontend/src/utilComponent/ProductCard.jsx
  frontend/src/utilComponent/SideDishStore.jsx
  frontend/src/utilComponent/carousel/Carousel.jsx
  frontend/src/utilComponent/modal/Modal.jsx
  frontend/src/utilComponent/modal/ModalCloseButton.jsx
Labels: FE, enhancement

#58 fix: hover 버그 수정
  frontend/src/utilComponent/ProductCard.jsx
Labels: FE, bug

#59 [FE] 서브 콘텐츠, 상세 페이지 버그 수정
  frontend/src/detail/Detail.jsx
  frontend/src/detail/DetailBottom.jsx
  frontend/src/detail/DetailTopGallery.jsx
  frontend/src/subContents/SubContents.jsx
  frontend/src/utilComponent/SideDishStore.jsx
  frontend/src/utilComponent/carousel/CarouselArrowBtn.jsx
Labels: FE, bug

#60 [FE] API 적용 완료
  frontend/package.json
  frontend/src/detail/Detail.jsx
  frontend/src/detail/DetailBottom.jsx
  frontend/src/detail/DetailTop.jsx
  frontend/src/detail/DetailTopGallery.jsx
  frontend/src/detail/DetailTopInfo.jsx
  frontend/src/mainContents/MainContentsContainer.jsx
  frontend/src/ref.jsx
  frontend/src/setupProxy.js
  frontend/src/subContents/SubContents.jsx
  frontend/src/utilComponent/ProductCard.jsx
Labels: BE, FE

#61 [BE] Feat/order
  backend/.idea/gradle.xml
  backend/build.gradle
  backend/src/main/java/develop/baminchan/SidedishApplication.java
  backend/src/main/java/develop/baminchan/controller/BanchanController.java
  backend/src/main/java/develop/baminchan/controller/CategoryController.java
  backend/src/main/java/develop/baminchan/controller/OrderController.java
  backend/src/main/java/develop/baminchan/entity/Order.java
  backend/src/main/java/develop/baminchan/service/OrderService.java
  backend/src/main/resources/application.properties
  backend/src/test/java/develop/baminchan/SidedishApplicationTests.java
Labels: BE, enhancement
